name: Build LineageOS 22.2 Kernel with Clang r536225
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_kernel:
    runs-on: ubuntu-latest
    steps:

      - name: Download custom config file (1.txt)
        run: |
          git clone https://github.com/LineageOS/android_kernel_oneplus_sm8150.git --depth=1 -b lineage-22.2
          

      - name: Clone Clang r536225 toolchain
        run: |
          # 克隆指定Clang工具链
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r536225 clang --depth=1

      - name: Set up build environment
        run: |
          sudo apt-get update
          # 保留基础依赖，移除GCC交叉编译器
          sudo apt-get install -y bc bison flex libncurses5-dev libssl-dev python3-pip device-tree-compiler
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu bc bison flex libncurses5-dev libssl-dev python3-pip device-tree-compiler libelf-dev

      - name: Configure kernel with custom config
        run: |
  
          cd android_kernel_oneplus_sm8150
          curl -o ./arch/arm64/configs/1_deconfig https://github.com/mingmingzhichu/build/raw/refs/heads/main/1.txt
          export ARCH=arm64
          export SUBARCH=arm64
          # 配置Clang工具链路径
          export PATH=$(pwd)/../clang/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=clang
          export CXX=clang++
          export LD=ld.lld
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export STRIP=llvm-strip

          # 加载默认配置并合并自定义配置
          make 1_deconfig

      - name: Build kernel with Clang
        run: |
          cd android_kernel_oneplus_sm8150
          # 使用Clang编译，保留多核加速
          make -j$(nproc)

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: kernel-clang-output
          path: android_kernel_oneplus_sm8150/arch/arm64/boot/Image.gz-dtb
