name: Build LineageOS 22.2 Kernel for hotdogb

on:
  workflow_dispatch:  # 手动触发构建

env:
  DEVICE: hotdogb
  KERNEL_REPO: "https://github.com/LineageOS/android_kernel_oneplus_hotdogb"  # 内核仓库
  KERNEL_BRANCH: "lineage-22.2"  # 内核分支
  DEVICE_TREE_REPO: "https://github.com/LineageOS/android_device_oneplus_hotdogb"  # 设备树仓库
  DEVICE_TREE_BRANCH: "lineage-22.2"
  TOOLCHAIN_REPO: "https://github.com/kdrag0n/proton-clang"  # Clang工具链
  TOOLCHAIN_BRANCH: "main"
  ARCH: arm64
  CROSS_COMPILE: "aarch64-linux-gnu-"
  CC: "clang"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. 安装依赖（Ubuntu环境）
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git-lfs python3 python3-distutils cpio bc bison flex \
            libssl-dev libelf-dev libncurses-dev zlib1g-dev \
            device-tree-compiler bc lzop

      # 2. 设置Clang工具链
      - name: Setup Toolchain
        run: |
          git clone --depth 1 -b $TOOLCHAIN_BRANCH $TOOLCHAIN_REPO
          export PATH="$PATH:$(pwd)/proton-clang/bin"
          echo "PATH=$PATH" >> $GITHUB_ENV

      # 3. 克隆内核和设备树源码
      - name: Clone Sources
        run: |
          git clone --depth 1 -b $KERNEL_BRANCH $KERNEL_REPO kernel
          git clone --depth 1 -b $DEVICE_TREE_BRANCH $DEVICE_TREE_REPO device

      # 4. 生成内核配置
      - name: Generate Config
        run: |
          cd kernel
          # 使用设备默认配置初始化
          make O=../kernel-build $DEVICE-defconfig
          # 可选：交互式配置
          # make O=../kernel-build menuconfig

      # 5. 编译内核
      - name: Compile Kernel
        run: |
          cd kernel
          make -j$(nproc) O=../kernel-build \
            ARCH=$ARCH \
            CROSS_COMPILE=$CROSS_COMPILE \
            CC=$CC

      # 6. 打包产物
      - name: Package Release
        run: |
          mkdir -p release
          cp kernel-build/arch/arm64/boot/Image.gz-dtb release/kernel.img
          zip -r9 release/lineage22.2-hotdogb-kernel.zip release/

      # 7. 上传编译产物到GitHub Release
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/lineage22.2-hotdogb-kernel.zip
          asset_name: lineage22.2-hotdogb-kernel.zip
          asset_content_type: application/zip
