name: Build LineageOS 22.2 Kernel for hotdogb

on:
  workflow_dispatch:  # 手动触发构建
  push:
    branches:
      - main  # 当 main 分支更新时自动触发

env:
  DEVICE: hotdogb
  KERNEL_REPO: "https://github.com/LineageOS/android_kernel_oneplus_sm8150"  # 替换为实际内核仓库
  KERNEL_BRANCH: "lineage-22.2"  # 内核分支
  DEVICE_TREE_REPO: "https://github.com/LineageOS/android_device_oneplus_hotdogb"  # 设备树仓库
  DEVICE_TREE_BRANCH: "lineage-22.2"
  TOOLCHAIN_REPO: "https://github.com/kdrag0n/proton-clang"  # Clang 工具链
  TOOLCHAIN_BRANCH: "main"
  ARCH: arm64
  CROSS_COMPILE: "aarch64-linux-gnu-"
  CC: "clang"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 设置 Clang 工具链
      - name: Setup Toolchain
        run: |
          git clone --depth 1 -b $TOOLCHAIN_BRANCH $TOOLCHAIN_REPO
          export PATH="$PATH:$(pwd)/proton-clang/bin"
          echo "PATH=$PATH" >> $GITHUB_ENV

      # 安装依赖
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs python3 python3-distutils cpio bc bison flex libssl-dev

      # 克隆内核源码
      - name: Clone Kernel Source
        run: |
          git clone --depth 1 -b $KERNEL_BRANCH $KERNEL_REPO kernel
          git clone --depth 1 -b $DEVICE_TREE_BRANCH $DEVICE_TREE_REPO device

      # 生成内核配置
      - name: Generate Kernel Config
        run: |
          cd kernel
          make O=../kernel_build $DEVICE-defconfig
          make O=../kernel_build menuconfig  # 可选：交互式配置

      # 编译内核
      - name: Compile Kernel
        run: |
          cd kernel
          make -j$(nproc) O=../kernel_build \
            ARCH=$ARCH \
            CROSS_COMPILE=$CROSS_COMPILE \
            CC=$CC

      # 打包产物
      - name: Package Release
        run: |
          mkdir -p release
          cp kernel/build/Image.gz-dtb release/
          zip -r9 release/lineage22.2-hotdogb-kernel.zip release/

      # 上传产物
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/lineage22.2-hotdogb-kernel.zip
          asset_name: lineage22.2-hotdogb-kernel.zip
          asset_content_type: application/zip
