name: Build LineageOS 22.1 Kernel for hotdogb

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * 0'  # 每周日自动构建（可选）

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检查环境与安装依赖
        run: |
          sudo apt update
          # Android 15编译依赖（新增lib32zstd-dev等）
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev lib32zstd-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          # 安装repo工具
          mkdir -p ~/.local/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.local/bin/repo
          chmod a+x ~/.local/bin/repo
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          # 初始化git lfs
          git lfs install
          # 配置ccache加速
          ccache -M 50G
          echo "USE_CCACHE=1" >> $GITHUB_ENV

      - name: 同步LineageOS 22.1源码
        run: |
          mkdir -p lineageos-workspace && cd lineageos-workspace
          # 初始化LOS 22.1分支（基于Android 15）
          repo init -u https://github.com/LineageOS/android.git -b lineage-22.1 --git-lfs --depth=1
          # 添加hotdogb设备仓库（LOS 22.1适配版）
          mkdir -p .repo/local_manifests
          cat > .repo/local_manifests/roomservice.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <!-- 设备配置（需LOS 22.1兼容版本） -->
            <project name="LineageOS/android_device_oneplus_hotdogb" path="device/oneplus/hotdogb" remote="github" revision="lineage-22.1" />
            <!-- 内核仓库（SM8150系列LOS 22.1分支） -->
            <project name="LineageOS/android_kernel_oneplus_sm8150" path="kernel/oneplus/sm8150" remote="github" revision="lineage-22.1" />
            <!-- 厂商驱动（更新至Android 15兼容版本） -->
            <project name="TheMuppets/proprietary_vendor_oneplus" path="vendor/oneplus" remote="github" />
          </manifest>
          EOF
          # 同步源码（仅最新提交，减少体积）
          repo sync -c -j$(nproc) --no-clone-bundle --no-tags

      - name: 配置设备驱动与编译环境
        run: |
          cd lineageos-workspace
          # 加载环境变量
          source build/envsetup.sh
          # 处理私有驱动（Android 15需更新blobs）
          breakfast hotdogb || true  # 忽略首次缺失提示
          # 从镜像下载Android 15兼容的blobs（需提前准备）
          # wget https://your-mirror/hotdogb-los22-blobs.zip && unzip -q hotdogb-los22-blobs.zip -d vendor/oneplus/hotdogb/
          breakfast hotdogb  # 重新加载配置

      - name: 集成KernelSU与内核配置
        run: |
          cd lineageos-workspace/kernel/oneplus/sm8150
          # 应用最新KernelSU补丁（适配Android 15）
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          # 启用Android 15必需的内核选项
          echo "CONFIG_KPROBES=y" >> arch/arm64/configs/lineageos_hotdogb_defconfig
          echo "CONFIG_SECURITY_SELINUX_DEVELOP=y" >> arch/arm64/configs/lineageos_hotdogb_defconfig  # SELinux调试（可选）
          # 清理旧配置
          make mrproper

      - name: 编译内核与设备树
        run: |
          cd lineageos-workspace
          source build/envsetup.sh
          breakfast hotdogb
          # 编译内核、dtb、dtbo（Android 15需dtbo签名）
          mka kernel dtbimage dtboimage
          # 验证产物
          ls -lh out/target/product/hotdogb/{kernel,dtb.img,dtbo.img}

      - name: 用Anykernel3打包（适配Android 15）
        run: |
          # 克隆Anykernel3并配置
          git clone https://github.com/osm0sis/AnyKernel3.git ak3
          # 复制编译产物
          cp lineageos-workspace/out/target/product/hotdogb/kernel ak3/Image.lz4
          cp lineageos-workspace/out/target/product/hotdogb/dtb.img ak3/dtb
          cp lineageos-workspace/out/target/product/hotdogb/dtbo.img ak3/dtbo.img
          # 配置Anykernel脚本（适配A/B分区与Android 15）
          cat > ak3/anykernel.sh << EOF
          properties() { '
          kernel.string=LOS 22.1 Kernel with KSu for hotdogb (Android 15)
          do.devicecheck=1
          do.modules=0
          do.systemless=1
          device.name1=hotdogb
          device.name2=OnePlus7TPro
          supported.versions=15
          '; }
          block=/dev/block/bootdevice/by-name/boot
          is_slot_device=1;
          . tools/ak3-core.sh;
          dump_boot;
          write_boot;
          EOF
          # 打包ZIP
          cd ak3 && zip -r9 ../hotdogb-los22-kernel-ksu.zip * -x .git* README.md

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: hotdogb-los22.1-kernel
          path: hotdogb-los22-kernel-ksu.zip
          retention-days: 7  # 产物保留7天
