name: Build LineageOS 22.2 Kernel with kernel.mk (Fixed)
on: 
  workflow_dispatch:

jobs:
  build_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: 检查基础代码
        run: |
          git clone https://github.com/LineageOS/android_kernel_oneplus_sm8150.git -b lineage-22.2 --depth=1
          git clone https://github.com/LineageOS/android_vendor_lineage.git vendor/lineage --depth=1

      - name: 克隆 Clang 工具链
        run: |
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r536225 clang --depth=1

      - name: 配置构建环境
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu bc bison flex \
            libncurses5-dev libssl-dev python3-pip \
            device-tree-compiler libelf-dev make

      - name: 创建 Makefile 入口脚本
        run: |
          # 创建临时 Makefile 用于调用 kernel.mk 逻辑
          cat > android_kernel_oneplus_sm8150/build_kernel.mk << 'EOF'
          include ../vendor/lineage/build/tasks/kernel.mk

          # 定义必要变量
          TARGET_KERNEL_CONFIG := vendor/sm8150-perf_defconfig
          TARGET_KERNEL_CLANG_COMPILE := true
          KERNEL_ARCH := arm64
          KERNEL_CLANG_TRIPLE := aarch64-linux-gnu-
          TARGET_KERNEL_CLANG_PATH := $(CURDIR)/../clang
          CROSS_COMPILE := aarch64-linux-gnu-
          BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
          KERNEL_OUT := $(CURDIR)/kernel_out
          KERNEL_SRC := $(CURDIR)

          # 自定义目标：生成配置
          generate_config:
              mkdir -p $(KERNEL_OUT)
              $(call make-kernel-config,$(KERNEL_OUT),$(TARGET_KERNEL_CONFIG))
              
          # 自定义目标：编译内核
          build_image: generate_config
              $(call make-kernel-target,$(BOARD_KERNEL_IMAGE_NAME))
          EOF

      - name: 生成内核配置（基于 kernel.mk）
        run: |
          cd android_kernel_oneplus_sm8150
          # 使用 Make 命令执行，而非直接在 Bash 中 source
          make -f build_kernel.mk generate_config
          # 验证配置文件
          if [ ! -f "kernel_out/.config" ]; then
            echo "配置生成失败！"
            exit 1
          fi

      - name: 编译内核
        run: |
          cd android_kernel_oneplus_sm8150
          make -f build_kernel.mk build_image

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: lineage-kernel-output
          path: |
            android_kernel_oneplus_sm8150/kernel_out/arch/arm64/boot/Image.gz-dtb
            android_kernel_oneplus_sm8150/kernel_out/.config
