name: debugger-action
on:
  workflow_dispatch:  # 手动触发（在 GitHub Actions 页面点击“Run workflow”启动）
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取仓库代码到 Runner

      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3-master.zip
          path: ~/AnyKernel3-master/
